### ISSUE TITLE
Test and Report

### ISSUE THREAD

**Issue by Alhindi66** [Ch33chOficial/LordPhish#4]
Hi my dear,

first i have to say u really did a great Job i fell in love with your Tool its way better then Blackeye 2.0 since this one is much more updated..

however i found those errors and am hoping you would update them very soon !! 

**THE MOST IMPORTANT ONE IS ICLOUD THE PAGE IS FROM 2014 Please update the new i cloud log in page from 2021**

insta login page is old and copyrights are from 2018

facebook doesnt work at all (also in blackeye doenst work)

twitter login page is not new 

google is not in english and facebook mobile also
after log in to google nothing shows up in lordphish

origin login page shows (not found)

steam works but the login page is not the new one 

yahoo shows (lord.sh: line 1016: cd: sites/yahoo: No such file or directory ) link is there but no connection

linkedin login page shows (not found)

Protomail login page shows (not found)

wordpress is not new 

microsoft windows store (lord.sh: line 661: serverMicrosoft: command not found )

Xbox login works fine

instafollower IG page has no images and we dont get any login infos in lordphish

ebay login page is not new but works

LOL is not in english and login button doesnt work

pintrest> lord.sh: line 1016: cd: sites/pinterest: No such file or directory  (link Failed to complete tunnel connection)

whatsapp doenst show the login info in Lordphish but its not that important since its only the nummber

amazon login page doenst seem to send the infos,, so the account and passord stay empty

Gmail login page also has problem and doenst send any info  also no image on the page

i only tested the important stuff i dont know about the rest 
but it would be great to update 

greetings

**Comment by Ch33chOficial** [comment]
Thanks friend, I am preparing a mega update of all pages, it may take a while to be released but everything will be updated for the pages of 2021, thanks again for the preference ...

**Comment by Alhindi66** [comment]
> Thanks friend, I am preparing a mega update of all pages, it may take a while to be released but everything will be updated for the pages of 2021, thanks again for the preference ...

Glad to hear that  
thank you
